name: ci
on:
  push:
    branches:
      - master

jobs:
  premerge:
    name: premerge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Compile
        run: yarn tsc --noEmit
      - name: Lint
        run: yarn lint
      - name: Check Format
        run: yarn prettier . --check
      - name: Build
        run: yarn build
